/**
 * monitor-utils.ts — Content normalization and fingerprinting utilities
 * for authoritative tax source change detection (Section 6 & 7).
 *
 * Designed to prevent false positives by removing timestamps, dynamic scripts,
 * ephemeral markup, and non-semantic whitespace before computing SHA-256 fingerprints.
 */

import { createHash } from 'node:crypto';

/**
 * Normalizes HTML/text content from an authoritative tax source.
 * Strips volatile dynamic markup, server timestamps, analytics scripts, and collapses whitespace.
 */
export function normalizeSourceContent(content: string, format: 'html' | 'pdf' = 'html'): string {
  if (!content) return '';

  if (format === 'html') {
    let cleaned = content;

    // 1. Remove script, style, noscript, and iframe tags and their contents
    cleaned = cleaned.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, ' ');
    cleaned = cleaned.replace(/<style\b[^<]*(?:(?!<\/style>)<[^<]*)*<\/style>/gi, ' ');
    cleaned = cleaned.replace(/<noscript\b[^<]*(?:(?!<\/noscript>)<[^<]*)*<\/noscript>/gi, ' ');
    cleaned = cleaned.replace(/<iframe\b[^<]*(?:(?!<\/iframe>)<[^<]*)*<\/iframe>/gi, ' ');

    // 2. Remove HTML comments
    cleaned = cleaned.replace(/<!--[\s\S]*?-->/g, ' ');

    // 3. Remove common ephemeral session tokens, CSRF tokens, and request IDs
    cleaned = cleaned.replace(/(?:_csrf|csrf_token|sessionId|session_id|nonce|requestId)=["']?[a-zA-Z0-9_\-]+["']?/gi, ' ');

    // 4. Remove ISO timestamps and dynamic date-time patterns
    cleaned = cleaned.replace(/\b\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})?\b/gi, ' ');
    cleaned = cleaned.replace(/\b(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun),\s+\d{1,2}\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{4}\s+\d{2}:\d{2}:\d{2}\s+(?:GMT|UTC|[A-Z]{3})\b/gi, ' ');

    // 5. Strip remaining HTML tags
    cleaned = cleaned.replace(/<[^>]+>/g, ' ');

    // 6. Decode common entities
    cleaned = cleaned
      .replace(/&nbsp;/g, ' ')
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'");

    // 7. Normalize all whitespace sequences to a single space
    cleaned = cleaned.replace(/\s+/g, ' ').trim();

    return cleaned;
  }

  // Format is PDF or plain text
  return content.replace(/\s+/g, ' ').trim();
}

/**
 * Computes a SHA-256 fingerprint for normalized content.
 */
export function computeFingerprint(content: string): string {
  return createHash('sha256').update(content, 'utf8').digest('hex');
}

export interface SourceChangeRecord {
  id: string;
  authority: string;
  title: string;
  sourceUrl: string;
  timestamp: string;
  previousFingerprint: string;
  newFingerprint: string;
  domain: string;
  affectedTaxPeriod: string;
  requiresManualReview: boolean;
}

/**
 * Formats a GitHub issue payload for a detected tax source change.
 * Enforces the strict rule: "not authoritative — human review required. No rate change is ever applied based on AI interpretation alone."
 */
export function formatChangeIssuePayload(change: SourceChangeRecord): { title: string; body: string } {
  const title = `[Tax Source Alert] Potential regulatory change detected: ${change.authority} (${change.id})`;

  const body = `## ⚠️ Regulatory Source Change Detected

An automated scheduled check detected a content update in an authoritative tax source.

### Change Metadata
- **Source ID**: \`${change.id}\`
- **Authority**: **${change.authority}**
- **Document Title**: ${change.title}
- **Source URL**: ${change.sourceUrl}
- **Tax Domain**: \`${change.domain}\`
- **Likely Affected Periods**: \`${change.affectedTaxPeriod}\`
- **Detected On**: \`${change.timestamp}\`
- **Previous Fingerprint (SHA-256)**: \`${change.previousFingerprint}\`
- **New Fingerprint (SHA-256)**: \`${change.newFingerprint}\`

---

### Mandatory Human Approval Gate (Section 8)

> [!WARNING]
> **NOT AUTHORITATIVE — HUMAN REVIEW REQUIRED.**
> This alert was generated by change detection. Under no circumstances should tax rates, slabs, or deduction rules be modified without human review and citation of official notifications/circulars. No rate change is ever applied based on AI interpretation alone.

### Required Approval Lifecycle
- [ ] **Step 1: Primary Source Verification** — Inspect official circular / gazette notification at ${change.sourceUrl}.
- [ ] **Step 2: Legal Impact Assessment** — Confirm whether statutory rates, thresholds, or exemptions were changed for existing or upcoming periods.
- [ ] **Step 3: Draft Data Update** — If rates changed, draft a new versioned record under \`src/data/tax/india/${change.domain}/\` (preserving historical records).
- [ ] **Step 4: Schema & Regression Testing** — Run \`npm test\` and \`npm run build\` to verify strict schema validation.
- [ ] **Step 5: Code Review & Merge** — Review PR with human sign-off before deploying to production.
`;

  return { title, body };
}
